# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: v3.7.0.1
  hooks:
    - id: shfmt
      args: ["-w", "-i", "4", "-ci"]

- repo: https://github.com/crate-ci/typos
  rev: v1.29.5
  hooks:
    - id: typos

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint-docker

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
    - id: shellcheck
