services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bropkg/webroot:/var/www/html:ro
      - ./data/certbot/letsencrypt:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/certbot/mozilla-dhparam.txt:/etc/nginx/mozilla-dhparam.txt:ro

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile.php
      target: final
    restart: always
