services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bropkg/webroot:/var/www/html:ro

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile.php
      target: final
    restart: always
