FROM nginx:1.27.3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
    certbot=2.1.0-4 \
    cron=3.0pl1-162 \
    python3-certbot-nginx=2.1.0-2 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY docker/nginx-default.conf /etc/nginx/conf.d/default.conf
