FROM nginx:1.27.3

RUN apt update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    certbot \
    cron \
    python3-certbot-nginx

COPY docker/nginx-default.conf /etc/nginx/conf.d/default.conf
