services:
  nginx:
    image: nginx:1.27.3
    volumes:
      - ./nginx-certtool.conf:/etc/nginx/conf.d/default.conf
      - ../data/certbot/letsencrypt:/etc/letsencrypt:ro
      - ../data/certbot/www:/var/www/certbot:ro
    ports:
      - 80:80
